ALTER TABLE sticky_notes ADD COLUMN IF NOT EXISTS z int NOT NULL DEFAULT 0;
ALTER TABLE board_photos ADD COLUMN IF NOT EXISTS z int NOT NULL DEFAULT 0;
ALTER TABLE board_receipts ADD COLUMN IF NOT EXISTS z int NOT NULL DEFAULT 0;
ALTER TABLE board_papers ADD COLUMN IF NOT EXISTS z int NOT NULL DEFAULT 0;
ALTER TABLE board_images ADD COLUMN IF NOT EXISTS z int NOT NULL DEFAULT 0;
